ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
petclinic_ip: "192.168.66.8"
application_ip: "192.168.66.9"
nexus_registry: "nexus.local.internship:5001"
image_name: "spring-petclinic-ar"
image_tag: "latest"

container_name: "spring-petclinic-ar"
app_port: 8080
host_port: 8085
