services:
  spring-petclinic:
    build:
      context: ./
    image: spring-petclinic:latest
    ports:
      - "8079:8080"     
      - "9404:9404"     
    networks:
      - spring-network
    privileged: true            
    volumes:
      - /proc:/host_proc:ro     

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - spring-network
    depends_on:
      - spring-petclinic

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - spring-network
    depends_on:
      - prometheus

volumes:
  grafana_data:

networks:
  spring-network:
    driver: bridge
