server:
  http_listen_port: 9080
  grpc_listen_port: 9096   
  log_level: info

positions:
  filename: ./promtail-positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-petclinic-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-petclinic
          __path__: ./pet.log
